Update test-release_container-dev_app_c30cc70_env_0b5e21b.yaml

diff --git a/.github/workflows/test-release_container-dev_app_c30cc70_env_0b5e21b.yaml b/.github/workflows/test-release_container-dev_app_c30cc70_env_0b5e21b.yaml
--- a/.github/workflows/test-release_container-dev_app_c30cc70_env_0b5e21b.yaml
+++ b/.github/workflows/test-release_container-dev_app_c30cc70_env_0b5e21b.yaml
@@ -75,76 +75,76 @@ jobs:
                   # Minifying Json
                   jq -c '.' trivy_results.json > trivy_results.min.json
                   
-      - name: 'Run :: Evaluate Trivy Results'
-        run: |2-
+      # - name: 'Run :: Evaluate Trivy Results'
+      #   run: |2-
              
-                  if jq -e '.Results | map(select(.Vulnerabilities)) | length > 0' trivy_results.min.json >/dev/null; then
-                    echo "Vulnerabilities detected!"
-                    jq '.Results[] | {Target: .Target, Vulnerabilities: .Vulnerabilities[] | {ID: .VulnerabilityID, Severity: .Severity, Description: .Description}}' trivy_results.min.json
-                    exit 1
-                  fi
+      #             if jq -e '.Results | map(select(.Vulnerabilities)) | length > 0' trivy_results.min.json >/dev/null; then
+      #               echo "Vulnerabilities detected!"
+      #               jq '.Results[] | {Target: .Target, Vulnerabilities: .Vulnerabilities[] | {ID: .VulnerabilityID, Severity: .Severity, Description: .Description}}' trivy_results.min.json
+      #               exit 1
+      #             fi
                   
-      - name: 'Run :: Trivy Filesystem Scan (Including Trivy Ignores)'
-        run: |2-
+      # - name: 'Run :: Trivy Filesystem Scan (Including Trivy Ignores)'
+      #   run: |2-
 
-                  docker run --rm -v "${PWD}:/src" aquasec/trivy fs /src --severity HIGH --format json --quiet --list-all-pkgs > trivy_results.json
-                  # Minifying Json
-                  jq -c '.' trivy_results.json > trivy_results.min.json
+      #             docker run --rm -v "${PWD}:/src" aquasec/trivy fs /src --severity HIGH --format json --quiet --list-all-pkgs > trivy_results.json
+      #             # Minifying Json
+      #             jq -c '.' trivy_results.json > trivy_results.min.json
                   
-      - name: 'Run :: Upload Code Scan Reports'
-        env:
-          RUN_ID: ${{ github.run_id }}
-        run: |2-
+      # - name: 'Run :: Upload Code Scan Reports'
+      #   env:
+      #     RUN_ID: ${{ github.run_id }}
+      #   run: |2-
 
-                  echo "Uploading Code Scan Report" 
-                  SARIF_FILE="semgrep_results.json"
-                  if [ -n "$SARIF_FILE" ]; then
-                    cat "$SARIF_FILE" > ${{ env.COMMIT_ID }}-code-scan-report.sarif
-                    echo "Uploading Code Quality Results to S3 :: ${{ env.COMMIT_ID }}-code-scan-report.sarif"
+      #             echo "Uploading Code Scan Report" 
+      #             SARIF_FILE="semgrep_results.json"
+      #             if [ -n "$SARIF_FILE" ]; then
+      #               cat "$SARIF_FILE" > ${{ env.COMMIT_ID }}-code-scan-report.sarif
+      #               echo "Uploading Code Quality Results to S3 :: ${{ env.COMMIT_ID }}-code-scan-report.sarif"
            
-                    response=$(curl -X POST -F 'file=@${{ env.COMMIT_ID }}-code-scan-report.sarif' -F 'provider=aws' -F 'resourceType=code-scan-report' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/code-scan-reports/' -F 'pipelineRunId=${{ env.RUN_ID }}'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
+      #               response=$(curl -X POST -F 'file=@${{ env.COMMIT_ID }}-code-scan-report.sarif' -F 'provider=aws' -F 'resourceType=code-scan-report' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/code-scan-reports/' -F 'pipelineRunId=${{ env.RUN_ID }}'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
 
-                    if echo "$response" | grep -q '"success":true'; then
-                      echo "SUCCESS :: $response"
-                    else
-                      echo "FAILED :: $response"
-                    fi
+      #               if echo "$response" | grep -q '"success":true'; then
+      #                 echo "SUCCESS :: $response"
+      #               else
+      #                 echo "FAILED :: $response"
+      #               fi
 
-                  else
-                      echo "SARIF file not found."
-                  fi
+      #             else
+      #                 echo "SARIF file not found."
+      #             fi
 
-                  echo "Uploading Code Vulnerability Report" 
-                  SARIF_FILE="trivy_results.min.json"
-                  if [ -n "$SARIF_FILE" ]; then
-                    cat "$SARIF_FILE" > ${{ env.COMMIT_ID }}-code-vulnerability-report.sarif
-                    echo "Uploading Code Vulnerability Results to S3 :: ${{ env.COMMIT_ID }}-code-vulnerability-report.sarif"
+      #             echo "Uploading Code Vulnerability Report" 
+      #             SARIF_FILE="trivy_results.min.json"
+      #             if [ -n "$SARIF_FILE" ]; then
+      #               cat "$SARIF_FILE" > ${{ env.COMMIT_ID }}-code-vulnerability-report.sarif
+      #               echo "Uploading Code Vulnerability Results to S3 :: ${{ env.COMMIT_ID }}-code-vulnerability-report.sarif"
            
-                    response=$(curl -X POST -F 'file=@${{ env.COMMIT_ID }}-code-vulnerability-report.sarif' -F 'provider=aws' -F 'resourceType=code-vulnerability-report' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/code-vulnerability-reports/' -F 'pipelineRunId=${{ env.RUN_ID }}'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
+      #               response=$(curl -X POST -F 'file=@${{ env.COMMIT_ID }}-code-vulnerability-report.sarif' -F 'provider=aws' -F 'resourceType=code-vulnerability-report' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/code-vulnerability-reports/' -F 'pipelineRunId=${{ env.RUN_ID }}'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
 
-                    if echo "$response" | grep -q '"success":true'; then
-                      echo "SUCCESS :: $response"
-                    else
-                      echo "FAILED :: $response"
-                    fi
+      #               if echo "$response" | grep -q '"success":true'; then
+      #                 echo "SUCCESS :: $response"
+      #               else
+      #                 echo "FAILED :: $response"
+      #               fi
 
-                  else
-                      echo "SARIF file not found."
-                  fi
+      #             else
+      #                 echo "SARIF file not found."
+      #             fi
                   
-                  echo "Uploading Trivy Ignore File" 
-                  if [ -n ".trivyignore" ]; then
-                    response=$(curl -X POST -F 'file=@.trivyignore' -F 'provider=aws' -F 'resourceType=trivy-ignore' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/trivy-ignore-file/${{ env.COMMIT_ID }}/' -F 'pipelineRunId=$RUN_ID'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
+      #             echo "Uploading Trivy Ignore File" 
+      #             if [ -n ".trivyignore" ]; then
+      #               response=$(curl -X POST -F 'file=@.trivyignore' -F 'provider=aws' -F 'resourceType=trivy-ignore' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/trivy-ignore-file/${{ env.COMMIT_ID }}/' -F 'pipelineRunId=$RUN_ID'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
 
-                    if echo "$response" | grep -q '"success":true'; then
-                      echo "SUCCESS :: $response"
-                    else
-                      echo "FAILED :: $response"
-                    fi
+      #               if echo "$response" | grep -q '"success":true'; then
+      #                 echo "SUCCESS :: $response"
+      #               else
+      #                 echo "FAILED :: $response"
+      #               fi
 
-                  else
-                      echo ".trivyignore file not found"
-                  fi
+      #             else
+      #                 echo ".trivyignore file not found"
+      #             fi
                   
   _status-pending:
     name: _status-pending
@@ -457,79 +457,79 @@ jobs:
           severity: ${{env.SCAN_SEVERITY}}
           hide-progress: true
         if: ${{ env.STEPS_CAN_PROCEED == 'true' }}
-      - name: 'Run :: Evaluate Trivy Results'
-        run: |2-
+      # - name: 'Run :: Evaluate Trivy Results'
+      #   run: |2-
 
-              # Minifying Json
-              jq -c '.' ${{ env.COMMIT_ID }}-image-vulnerability-report.json > ${{ env.COMMIT_ID }}-image-vulnerability-report.min.json
-              trivy_result=$(cat "${{ env.COMMIT_ID }}-image-vulnerability-report.min.json")
+      #         # Minifying Json
+      #         jq -c '.' ${{ env.COMMIT_ID }}-image-vulnerability-report.json > ${{ env.COMMIT_ID }}-image-vulnerability-report.min.json
+      #         trivy_result=$(cat "${{ env.COMMIT_ID }}-image-vulnerability-report.min.json")
 
-              # Set the desired severity level
-              desiredSeverity="${{ env.SCAN_SEVERITY }}"
-              IFS=',' read -ra severities <<< "$desiredSeverity"  # Split the severity string
+      #         # Set the desired severity level
+      #         desiredSeverity="${{ env.SCAN_SEVERITY }}"
+      #         IFS=',' read -ra severities <<< "$desiredSeverity"  # Split the severity string
 
-              # Print the tags array for debugging
-              jq '.runs[0].tool.driver.rules[].properties.tags' "${{ env.COMMIT_ID }}-image-vulnerability-report.json"
+      #         # Print the tags array for debugging
+      #         jq '.runs[0].tool.driver.rules[].properties.tags' "${{ env.COMMIT_ID }}-image-vulnerability-report.json"
 
-              VULNERABILITY_COUNT=0
+      #         VULNERABILITY_COUNT=0
 
-              for severity in "${severities[@]}"; do
-                count=$(jq --arg severity "$severity" '.runs[0].tool.driver.rules | map(select(.properties.tags and (.properties.tags | map(tostring) | index($severity) // empty))) | length' "${{ env.COMMIT_ID }}-image-vulnerability-report.json")
-                echo "Number of $severity vulnerabilities: $count"
-                VULNERABILITY_COUNT=$((VULNERABILITY_COUNT + count))
-              done
+      #         for severity in "${severities[@]}"; do
+      #           count=$(jq --arg severity "$severity" '.runs[0].tool.driver.rules | map(select(.properties.tags and (.properties.tags | map(tostring) | index($severity) // empty))) | length' "${{ env.COMMIT_ID }}-image-vulnerability-report.json")
+      #           echo "Number of $severity vulnerabilities: $count"
+      #           VULNERABILITY_COUNT=$((VULNERABILITY_COUNT + count))
+      #         done
 
-              echo "Total Number of vulnerabilities: $VULNERABILITY_COUNT"
+      #         echo "Total Number of vulnerabilities: $VULNERABILITY_COUNT"
 
-              if [ "$VULNERABILITY_COUNT" -gt 0 ]; then
-                echo "STEPS_CAN_PROCEED=false" >> $GITHUB_ENV
-                echo "VULNERABILITY_COUNT=$VULNERABILITY_COUNT" >> $GITHUB_ENV
-              fi
-              echo "ARE_TRIVY_RESULTS_EVALUATED=true" >> $GITHUB_ENV
+      #         if [ "$VULNERABILITY_COUNT" -gt 0 ]; then
+      #           echo "STEPS_CAN_PROCEED=false" >> $GITHUB_ENV
+      #           echo "VULNERABILITY_COUNT=$VULNERABILITY_COUNT" >> $GITHUB_ENV
+      #         fi
+      #         echo "ARE_TRIVY_RESULTS_EVALUATED=true" >> $GITHUB_ENV
               
-        if: ${{ env.STEPS_CAN_PROCEED == 'true' }}
-      - name: 'Run :: Upload Trivy Result To S3'
-        env:
-          RUN_ID: ${{ github.run_id }}
-        run: |2-
+      #   if: ${{ env.STEPS_CAN_PROCEED == 'true' }}
+      # - name: 'Run :: Upload Trivy Result To S3'
+      #   env:
+      #     RUN_ID: ${{ github.run_id }}
+      #   run: |2-
 
 
-              # Minifying Json
-              jq -c '.' ${{ env.COMMIT_ID }}-image-vulnerability-report.json > ${{ env.COMMIT_ID }}-image-vulnerability-report.min.json
+      #         # Minifying Json
+      #         jq -c '.' ${{ env.COMMIT_ID }}-image-vulnerability-report.json > ${{ env.COMMIT_ID }}-image-vulnerability-report.min.json
 
-              # Uploading Minified Trivy Resuls
-              response=$(curl -X POST -F 'file=@${{ env.COMMIT_ID }}-image-vulnerability-report.min.json' -F 'provider=aws' -F 'resourceType=image-vulnerability-report' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/image-vulnerability-reports/' -F 'pipelineRunId=$RUN_ID'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
+      #         # Uploading Minified Trivy Resuls
+      #         response=$(curl -X POST -F 'file=@${{ env.COMMIT_ID }}-image-vulnerability-report.min.json' -F 'provider=aws' -F 'resourceType=image-vulnerability-report' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/image-vulnerability-reports/' -F 'pipelineRunId=$RUN_ID'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
 
-              if echo "$response" | grep -q '"success":true'; then
-                echo "SUCCESS :: $response"
-              else
-                echo "FAILED :: $response"
-              fi
+      #         if echo "$response" | grep -q '"success":true'; then
+      #           echo "SUCCESS :: $response"
+      #         else
+      #           echo "FAILED :: $response"
+      #         fi
               
-              if [ -f ".trivyignore" ]; then
-                # Uploading trivyignore file
-                trivyignoreResponse=$(curl -X POST -F 'file=@.trivyignore' -F 'provider=aws' -F 'resourceType=trivy-ignore' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/trivy-ignore-file/${{ env.COMMIT_ID }}/' -F 'pipelineRunId=$RUN_ID'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
+      #         if [ -f ".trivyignore" ]; then
+      #           # Uploading trivyignore file
+      #           trivyignoreResponse=$(curl -X POST -F 'file=@.trivyignore' -F 'provider=aws' -F 'resourceType=trivy-ignore' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/trivy-ignore-file/${{ env.COMMIT_ID }}/' -F 'pipelineRunId=$RUN_ID'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
 
-                if echo "$trivyignoreResponse" | grep -q '"success":true'; then
-                  echo "SUCCESS :: $trivyignoreResponse"
-                else
-                  echo "FAILED :: $trivyignoreResponse"
-                fi
+      #           if echo "$trivyignoreResponse" | grep -q '"success":true'; then
+      #             echo "SUCCESS :: $trivyignoreResponse"
+      #           else
+      #             echo "FAILED :: $trivyignoreResponse"
+      #           fi
 
-              else
-                echo ".trivyignore file not found. Skipping the upload."
-              fi
+      #         else
+      #           echo ".trivyignore file not found. Skipping the upload."
+      #         fi
               
-        if: ${{ env.ARE_TRIVY_RESULTS_EVALUATED == 'true' }}
-      - name: 'Run :: Check Pipeline Safety'
-        run: |2-
+      #   if: ${{ env.ARE_TRIVY_RESULTS_EVALUATED == 'true' }}
+      # - name: 'Run :: Check Pipeline Safety'
+      #   run: |2-
 
-              if [ "${{ env.VULNERABILITY_COUNT }}" -gt 0 ]; then
-                echo "UN-SAFE to continue Pipeline"
-                exit 1
-              else
-                echo "SAFE to continue Pipeline"
-              fi
+      #         if [ "${{ env.VULNERABILITY_COUNT }}" -gt 0 ]; then
+      #           echo "UN-SAFE to continue Pipeline"
+      #           exit 1
+      #         else
+      #           echo "SAFE to continue Pipeline"
+      #         fi
               
       - name: 'Run :: Build, tag, and push image'
         run: docker push ${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}
